<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5Y6f5Yib6K6+6K6h');
$cfg_Cs[2]=array(0,2,1,'5Yib5oSP5ouN5pGE');
$cfg_Cs[3]=array(0,2,1,'5Lqa6ams6YCK');
$cfg_Cs[4]=array(0,17,1,'5b2x6KeG5Yib5L2c');
$cfg_Cs[5]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[6]=array(0,1,1,'6aaW6aG1YmFubmVy5Zu+');
$cfg_Cs[7]=array(0,18,1,'6aaW6aG15bqV6YOo5L+h5oGv');
$cfg_Cs[8]=array(0,1,1,'5paw6Ze7');
$cfg_Cs[9]=array(0,1,1,'5omL5py66L2u5pKt5Zu+');
?>