/asset/images/aboutWe/~typename~Active.png" alt="">
                <span class="title bigTitle">~typename~</span>
                <span class="english">~description~ +</span>
            </div>'}
            <div class="logoModule">
                <img src="[field:global.cfg_templets_skin/]/asset/images/aboutWe/[field:typename /].png" alt="">
                <span class="title bigTitle">[field:typename /]</span>
                <span class="english">[field:description /]+</span>
            </div>
            