<?php
$z[0]=Array("spaceurl","",148,166);
$z[0][4]=array();
$z[1]=Array("face","",195,208);
$z[1][4]=array();
$z[2]=Array("spaceurl","",249,267);
$z[2][4]=array();
$z[3]=Array("uname","",286,300);
$z[3][4]=array();
$z[4]=Array("spaceurl","",337,355);
$z[4][4]=array();
$z[5]=Array("spaceurl","",408,426);
$z[5][4]=array();
$z[6]=Array("spaceurl","",490,508);
$z[6][4]=array();
$z[7]=Array("rankname","",625,643);
$z[7][4]=array();
$z[8]=Array("jointime","",705,757);
$z[8][4]=array();
$z[8][4]['function']="MyDate('Y-m-d H:m',@me)";
$z[9]=Array("logintime","",819,872);
$z[9][4]=array();
$z[9][4]['function']="MyDate('Y-m-d H:m',@me)";

?>