
                        <li data-url='[field:typelink /]'>
                            <div class="titleBox">
                                <span></span>
                                <span>[field:typename /]</span>
                            </div>
                            <div class="contentBox" style="display: none">
                               [field:content /]
                            </div>
                        </li>
                    