<li>
                <a href="javascript:;">
                    <div class="imgBox">
                        <img src="[field:imglink /]" alt="">
                    </div>
                    <div class="textBox">
                        <span class="time">[field:pubdate function="MyDate('Y-m-d',@me)"/]</span>
                        <span class="title">[field:title /]</span>
                        <span class="content">[field:description /]</span>
                    </div>
                </a>
            </li>