<div class="footerModule">
        <img src="[field:global.cfg_templets_skin/]/asset/images/home/qqFooter.png" alt="">
        <span>[field:qq/]</span>
    </div>
    <div class="footerModule">
        <img src="[field:global.cfg_templets_skin/]/asset/images/home/mobileIcon.png" alt="">
        <span>[field:phone/]</span>
    </div>
    <div class="footerModule">
        <img src="[field:global.cfg_templets_skin/]/asset/images/home/location.png" alt="">
        <span>[field:address/]</span>
    </div>
    <div class="footerModule">
        <img src="[field:global.cfg_templets_skin/]/asset/images/home/erweima.png" class="erweima" alt="">
        <span>业务总监</span>
    </div>