<a href='[field:typelink /]'>
                <img src="[field:global.cfg_templets_skin/]asset/images/home/more.png" alt="">
              </a>
              {/dede}
            </div>
        </div>
        <div class="moduleContent">
            {dede:arclist row=10 orderby=pubdate flag='c' typeid=1 }
            <div class="imgModule">
               <a href='[field:arcurl/]'>
               [field:image/]    
               </a>        
            </div>
            {/dede:arclist}         
        </div>
    </div>
    <!--亚马逊设计-->
    <div class="productModule">
        <div class="moduleTitle">
            <img class="titleBackImg" src="{dede:global.cfg_templets_skin