
                        <li>
                            <a href='[field:typelink /]'>
                            <div class="titleBox">
                                <span></span>
                                <span>[field:typename /]</span>
                            </div>
                            <div class="contentBox" style="display: none">
                               [field:content /]
                            </div>
                            </a>
                        </li>
                    