<div class="footerModule">
        <img src="{dede:global.cfg_templets_skin/}/asset/images/home/qqFooter.png" alt="">
        <span>[field:qq/]</span>
    </div>
    <div class="footerModule">
        <img src="{dede:global.cfg_templets_skin/}/asset/images/home/mobileIcon.png" alt="">
        <span>xxxxxxxxx</span>
    </div>
    <div class="footerModule">
        <img src="{dede:global.cfg_templets_skin/}/asset/images/home/location.png" alt="">
        <span>xxxxxxxxx</span>
    </div>
    <div class="footerModule">
        <img src="{dede:global.cfg_templets_skin/}/asset/images/home/erweima.png" class="erweima" alt="">
        <span>xxxxxxxxx</span>
    </div>