<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/191009/1-191009150355.jpg ",93,239);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/191009/1-191009150355.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="200";
$z[1][4]['height']="60";
$z[2]=Array("img"," /uploads/allimg/191009/1-191009150400.jpg ",241,388);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/191009/1-191009150400.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="252";
$z[2][4]['height']="180";
$z[3]=Array("img"," /uploads/allimg/191009/1-191009150404.gif ",390,537);
$z[3][4]=array();
$z[3][4]['ddimg']="/uploads/allimg/191009/1-191009150404.gif";
$z[3][4]['text']="";
$z[3][4]['width']="125";
$z[3][4]['height']="114";

?>