<?php
$z[0]=Array("global","\r\n\r\n					 (@me%2!=0)? @me=\"<div class=\"itemModule moduleImg\">\":@me=\"<div class=\"itemModule moduleVideo\"></li>\";\r\n\r\n				",0,176);
$z[0][4]=array();
$z[0][4]['name']="autoindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("id","",217,228);
$z[1][4]=array();
$z[2]=Array("image","",253,268);
$z[2][4]=array();
$z[3]=Array("title","",314,329);
$z[3][4]=array();

?>