<?php
$z[0]=Array("include","",0,36);
$z[0][4]=array();
$z[0][4]['filename']="head2.htm";
$z[1]=Array("global","",67,99);
$z[1][4]=array();
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",156,188);
$z[2][4]=array();
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("field","\r\n          \r\n          <div class=\"smallModule\">\r\n          	  <img src=\"[field:imgsrc/]\" alt=\"\">\r\n       		</div>\r\n         ",526,714);
$z[3][4]=array();
$z[3][4]['name']="imgurls";
$z[3][4]['alt']="图片输出区";
$z[4]=Array("include","",739,779);
$z[4][4]=array();
$z[4][4]['filename']="footer22.html";
$z[5]=Array("include","",810,847);
$z[5][4]=array();
$z[5][4]['filename']="footer.htm";

?>