<?php
$z[0]=Array("include","",0,36);
$z[0][4]=array();
$z[0][4]['filename']="head2.htm";
$z[1]=Array("global","",67,99);
$z[1][4]=array();
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("field","",739,757);
$z[2][4]=array();
$z[2][4]['name']="body";
$z[3]=Array("include","",787,827);
$z[3][4]=array();
$z[3][4]['filename']="footer22.html";
$z[4]=Array("include","",858,895);
$z[4][4]=array();
$z[4][4]['filename']="footer.htm";

?>