[field:global runphp='yes' name=autoindex]$c
= '<div class="itemModule moduleVideo">'; if((@me % 1) == 0) @me = $c;
else @me = '<div class="itemModule moduleImg">';[/field:global]
                <a href="view.php?aid=[field:id/]">
                   
                	<img src='[field:picname /]'>
                    <div class="introduce">[field:title /]</div>
                </a>
            </div>