<a href='[field:typelink /]'>
               <img src="[field:global.cfg_templets_skin/]asset/images/home/more.png" alt="">
              </a>
              {/dede}
            </div>
        </div>
        <div class="moduleContent">
           {dede:arclist row=10 orderby=pubdate flag='c' typeid=2 }
            <a href='[field:arcurl/]'>
              <div class="imgModule">
                [field:image/]            
              </div>
            </a>
            {/dede:arclist}
        </div>
    </div>
<!--            视频拍摄-->
    <div class="productModule">
        <div class="moduleTitle">
            <img class="titleBackImg" src="{dede:global.cfg_templets_skin