

            <div class="logoModule" data-url="[field:typelink /]">
              <a href="list.php?tid=[field:id/]">
                <img src="[field:global.cfg_templets_skin/]/masset/images/public/[field:typename /].png" class="img" alt="">
                <img src="[field:global.cfg_templets_skin/]/masset/images/public/[field:typename /]Active.png" style='display:none;' class="imgActive" alt="">
                <span class="title">[field:typename /]</span>
                </a>
            </div>
        