<a href='[field:typelink /]'>
                <img src="[field:global.cfg_templets_skin/]asset/images/home/more.png" alt="">
              </a>
              {/dede}
            </div>
        </div>
        <div class="moduleContent">
            {dede:arclist row=10 orderby=pubdate flag='c' typeid=3 }
            <div class="imgModule">
              <a href='[field:arcurl/]'>
              [field:image/]   
              </a>          
            </div>
            {/dede:arclist}       
        </div>

        <div class="pageTop">
            <img src="{dede:global.cfg_templets_skin