<?php
$z[0]=Array("global","\$c\r\n= '<div class=\"itemModule moduleVideo\">'; if((@me % 1) == 0) @me = \$c;\r\nelse @me = '<div class=\"itemModule moduleImg\">';",0,181);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[0][4]['name']="autoindex";
$z[1]=Array("id","",221,232);
$z[1][4]=array();
$z[2]=Array("picname","",287,304);
$z[2][4]=array();
$z[3]=Array("title","",351,366);
$z[3][4]=array();

?>