<li>
                <a href="view.php?aid=[field:id/]">
                    <div class="imgBox">
                       [field:image  /]
                    </div>
                    <div class="textBox">
                        <span class="time">[field:pubdate function="MyDate('Y年m月d日',@me)"/]</span>
                        <span class="title">[field:title /]</span>
                        <span class="content">[field:description /]</span>
                    </div>
                </a>
            </li>