<?php
$z[0]=Array("spaceurl","",90,108);
$z[0][4]=array();
$z[1]=Array("face","",137,150);
$z[1][4]=array();
$z[2]=Array("spaceurl","",197,215);
$z[2][4]=array();
$z[3]=Array("uname","",234,248);
$z[3][4]=array();
$z[4]=Array("spaceurl","",298,316);
$z[4][4]=array();
$z[5]=Array("spaceurl","",394,412);
$z[5][4]=array();
$z[6]=Array("spaceurl","",483,501);
$z[6][4]=array();
$z[7]=Array("rankname","",630,648);
$z[7][4]=array();
$z[8]=Array("jointime","",716,768);
$z[8][4]=array();
$z[8][4]['function']="MyDate('Y-m-d H:m',@me)";
$z[9]=Array("logintime","",836,889);
$z[9][4]=array();
$z[9][4]['function']="MyDate('Y-m-d H:m',@me)";

?>