<a href='[field:typelink /]'>
                <img src="[field:global.cfg_templets_skin/]asset/images/home/more.png" alt="">
              </a>
              {/dede}
            </div>
        </div>
        <div class="moduleContent">
           {dede:arclist row=10 addfields='video' channelid='17' orderby=pubdate typeid=4  imgwidth='390' imgheight='350'}          
            <div class="imgModule videolist" ipath='[field:video/]' >
             
                 [field:image/]
                 <div class="vtit">[field:title/]</div>

                 <img src="[field:global.cfg_templets_skin/]/images/play.png" class="videoed"/>
           
            </div>
            {/dede:arclist}
    
            <div class="vidAlert"></div>
           
        </div>
    </div>
    <!--详情设计-->
    <div class="productModule">
        <div class="moduleTitle">
            <img class="titleBackImg" src="{dede:global.cfg_templets_skin