<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/191007/1-19100G44332.png ",93,239);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/191007/1-19100G44332.png";
$z[1][4]['text']="";
$z[1][4]['width']="1931";
$z[1][4]['height']="798";
$z[2]=Array("img"," /uploads/allimg/191007/1-19100G44339.png ",241,387);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/191007/1-19100G44339.png";
$z[2][4]['text']="";
$z[2][4]['width']="1940";
$z[2][4]['height']="798";
$z[3]=Array("img"," /uploads/allimg/191007/1-19100G44354.png ",389,535);
$z[3][4]=array();
$z[3][4]['ddimg']="/uploads/allimg/191007/1-19100G44354.png";
$z[3][4]['text']="";
$z[3][4]['width']="1940";
$z[3][4]['height']="798";

?>