<?php
$z[0]=Array("arclist","\r\n                    <div class=\"smallModule\">\r\n                        <a href='[field:arcurl/]'>\r\n                        <div class=\"imgBox\">\r\n                            <img src=\"[field:litpic/]\" alt=\"\">\r\n                        </div>\r\n                        <p>[field:title/]</p>\r\n                        </a>\r\n                    </div>\r\n                    ",308,735);
$z[0][4]=array();
$z[0][4]['row']="8";
$z[0][4]['type']="image.commend.";
$z[1]=Array("global","",964,996);
$z[1][4]=array();
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",1079,1111);
$z[2][4]=array();
$z[2][4]['name']="cfg_templets_skin";

?>