<?php
$z[0]=Array("global","",120,152);
$z[0][4]=array();
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",264,296);
$z[1][4]=array();
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",454,486);
$z[2][4]=array();
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",784,816);
$z[3][4]=array();
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",952,984);
$z[4][4]=array();
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("channel","\n    	  <a href='list.php?tid=[field:id/]'>[field:typename/]</a>\n    	",1091,1210);
$z[5][4]=array();
$z[5][4]['type']="top";
$z[5][4]['row']="10";
$z[6]=Array("global","",1268,1300);
$z[6][4]=array();
$z[6][4]['name']="cfg_templets_skin";

?>