<?php
$z[0]=Array("arclist","\r\n    <div class=\"footerModule\">\r\n        <img src=\"[field:global.cfg_templets_skin/]/asset/images/home/qqFooter.png\" alt=\"\">\r\n        <span>[field:qq/]</span>\r\n    </div>\r\n    <div class=\"footerModule\">\r\n        <img src=\"[field:global.cfg_templets_skin/]/asset/images/home/mobileIcon.png\" alt=\"\">\r\n        <span>[field:phone/]</span>\r\n    </div>\r\n    <div class=\"footerModule\">\r\n        <img src=\"[field:global.cfg_templets_skin/]/asset/images/home/location.png\" alt=\"\">\r\n        <span>[field:address/]</span>\r\n    </div>\r\n    <div class=\"footerModule\">\r\n        \r\n        <img src=\"[field:erweima function='GetOneImgUrl(@me,1)'/]\" class=\"erweima\" alt=\"\">\r\n        <span>业务总监</span>\r\n    </div>\r\n    ",26,847);
$z[0][4]=array();
$z[0][4]['aid']="9";
$z[0][4]['channelid']="18";
$z[0][4]['typeid']="7";
$z[0][4]['addfields']="qq,phone,address,erweima";
$z[0][4]['limit']="0,1";

?>