<?php
$z[0]=Array("global","",137,169);
$z[0][4]=array();
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",227,259);
$z[1][4]=array();
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",317,349);
$z[2][4]=array();
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",499,531);
$z[3][4]=array();
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",736,768);
$z[4][4]=array();
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",935,967);
$z[5][4]=array();
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",1130,1162);
$z[6][4]=array();
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("global","",1319,1351);
$z[7][4]=array();
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("channel","\r\n                <li><a href='list.php?tid=[field:id/]' [field:rel/]><span>[field:typename/]</span></a>\r\n                </li>",1453,1765);
$z[8][4]=array();
$z[8][4]['type']="top";
$z[8][4]['row']="10";
$z[8][4]['currentstyle']="<li class='hover'><a href='list.php?tid=~id~' ~rel~><span>~typename~</span></a> </li>";
$z[9]=Array("channel","\r\n\r\n            <div class=\"logoModule\" data-url=\"[field:typelink /]\">\r\n              <a href=\"list.php?tid=[field:id/]\">\r\n                <img src=\"[field:global.cfg_templets_skin/]/masset/images/public/[field:typename /].png\" class=\"img\" alt=\"\">\r\n                <img src=\"[field:global.cfg_templets_skin/]/masset/images/public/[field:typename /]Active.png\" style='display:none;' class=\"imgActive\" alt=\"\">\r\n                <span class=\"title\">[field:typename /]</span>\r\n                </a>\r\n            </div>\r\n        ",1780,2654);
$z[9][4]=array();
$z[9][4]['type']="top";
$z[9][4]['row']="10";
$z[9][4]['currentstyle']="<div class=\"logoModule logoModuleActive\"> <a href=\"list.php?tid=~id~\"> <img src=\"~global.cfg_templets_skin~/masset/images/public/~typename~Active.png\" class=\"imgActive\" alt=\"\"> <span class=\"title\">~typename~</span> </a> </div>";

?>