<?php
$z[0]=Array("channel","\r\n            <li><a href='[field:typeurl/]' [field:rel/]>[field:typename/]</a></li> ",147,374);
$z[0][4]=array();
$z[0][4]['type']="top";
$z[0][4]['row']="10";
$z[0][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[1]=Array("global","",482,514);
$z[1][4]=array();
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",665,697);
$z[2][4]=array();
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("arclist","\r\n            <div class='img'>\r\n                [field:erweima function='GetOneImgUrl(@me,0)'/]\r\n            </div>\r\n              ",770,1013);
$z[3][4]=array();
$z[3][4]['aid']="9";
$z[3][4]['channelid']="18";
$z[3][4]['typeid']="7";
$z[3][4]['addfields']="qq,phone,address,erweima";
$z[3][4]['limit']="0,1";

?>