<?php
$z[0]=Array("global","",61,89);
$z[0][4]=array();
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",102,121);
$z[1][4]=array();
$z[1][4]['name']="title";
$z[2]=Array("global","",122,148);
$z[2][4]=array();
$z[2][4]['name']="cfg_webname";
$z[3]=Array("include","",1667,1706);
$z[3][4]=array();
$z[3][4]['filename']="header_m.htm";
$z[4]=Array("list","\r\n							<li class=\"am-g am-list-item-desced am-list-item-thumbed am-list-item-thumb-left\">\r\n								<div class=\"am-u-sm-4 am-list-thumb\">\r\n									<a href=\"view.php?aid=[field:id/]\">\r\n										<img src=\"[field:litpic/]\" width=\"75px\" height=\"75px\">\r\n									</a>\r\n								</div>\r\n								<div class=\" am-u-sm-8 am-list-main\">\r\n									 <h3 class=\"am-list-item-hd\">\r\n            <a href=\"view.php?aid=[field:id/]\" class=\"\">[field:title/]</a>\r\n          </h3>\r\n									<div class=\"am-list-item-text\"><b>日期：</b>[field:pubdate function=\"GetDateTimeMK(@me)\"/] <b>点击：</b>[field:click/] <b>好评：</b>[field:scores/]</div>\r\n									<p class=\"intro\">[field:description/]...</p>\r\n								</div>\r\n							</li>",1990,2745);
$z[4][4]=array();
$z[4][4]['pagesize']="1";
$z[5]=Array("pagelist","",2878,2956);
$z[5][4]=array();
$z[5][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[5][4]['listsize']="1";
$z[6]=Array("arclist","\r\n							<li><a href=\"view.php?aid=[field:id/]\">[field:title/]</a>\r\n							</li>",3211,3358);
$z[6][4]=array();
$z[6][4]['row']="5";
$z[6][4]['orderby']="pubdate";
$z[6][4]['titlelen']="40";
$z[7]=Array("arclist","\r\n							<li><a href=\"view.php?aid=[field:id/]\">[field:title/]</a>\r\n							</li>",3519,3662);
$z[7][4]=array();
$z[7][4]['row']="5";
$z[7][4]['orderby']="hot";
$z[7][4]['titlelen']="40";
$z[8]=Array("include","",3717,3756);
$z[8][4]=array();
$z[8][4]['filename']="footer_m.htm";

?>