<?php
$z[0]=Array("include","",0,36);
$z[0][4]=array();
$z[0][4]['filename']="head2.htm";
$z[1]=Array("global","",67,99);
$z[1][4]=array();
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("list","\r\n            <div class=\"productModule\">\r\n                <a href='[field:arcurl /]'>\r\n                  <div class=\"imgBox\">\r\n                     [field:image/]\r\n                  </div>\r\n                  <p>[field:title/]</p>\r\n                </a>\r\n            </div>\r\n            ",481,804);
$z[2][4]=array();
$z[2][4]['pagesize']="10";
$z[3]=Array("pagelist","",868,924);
$z[3][4]=array();
$z[3][4]['listitem']="index,pre,next";
$z[3][4]['listsize']="10";
$z[4]=Array("include","",1239,1276);
$z[4][4]=array();
$z[4][4]['filename']="footer.htm";

?>