<?php
$z[0]=Array("include","",0,36);
$z[0][4]=array();
$z[0][4]['filename']="head2.htm";
$z[1]=Array("global","",67,99);
$z[1][4]=array();
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("arclist","\r\n            <div class=\"productModule\">\r\n                <a href='[field:arcurl /]'>\r\n                  <div class=\"imgBox\">\r\n                      <img src=\"[field:litpic/]\" alt=\"\">\r\n                  </div>\r\n                  <p>[field:title/]</p>\r\n                </a>\r\n            </div>\r\n           ",498,863);
$z[2][4]=array();
$z[2][4]['row']="8";
$z[2][4]['type']="image.commend.";
$z[3]=Array("pagelist","",927,983);
$z[3][4]=array();
$z[3][4]['listitem']="index,pre,next";
$z[3][4]['listsize']="10";
$z[4]=Array("include","",1236,1273);
$z[4][4]=array();
$z[4][4]['filename']="footer.htm";

?>